# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180412_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('random', 'Random'), ('non', 'None')], help_text='The order in which choices are displayed to the user.', max_length=30, null=True, verbose_name='Choice Order'),
        ),
    ]
